import re
import uuid
from typing import List, Dict, Any, Optional, Tuple
from api.models import SectionNode, TableData, DocumentTree


class TreeBuilder:
    """
    Parses Markdown generated by pymupdf4llm into a nested heading hierarchy tree
    and isolates embedded GFM markdown tables.
    """

    HEADING_REGEX = re.compile(r"^(#{1,6})\s+(.+)$")
    TABLE_ROW_REGEX = re.compile(r"^\s*\|(.+)\|\s*$")
    TABLE_DELIMITER_REGEX = re.compile(r"^\s*\|(?:\s*:?-+:?\s*\|)+\s*$")

    @classmethod
    def clean_heading_title(cls, raw_title: str) -> str:
        """Strips markdown formatting from heading titles for clean UI display."""
        title = raw_title.strip()
        # Remove leading hashes if present
        title = re.sub(r"^#{1,6}\s*", "", title)
        # Remove bold/italic markers
        title = re.sub(r"\*\*|\*|__|_", "", title)
        # Remove links [text](url) -> text
        title = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", title)
        # Remove trailing/leading special characters
        title = title.strip()
        return title if title else "Untitled Section"

    @classmethod
    def parse_table_block(cls, table_lines: List[str], section_id: str, page_num: int) -> Optional[TableData]:
        """Parses consecutive markdown table lines into structured TableData."""
        if len(table_lines) < 2:
            return None

        # Check for delimiter row
        has_delimiter = any(cls.TABLE_DELIMITER_REGEX.match(line) for line in table_lines)
        if not has_delimiter:
            return None

        headers: List[str] = []
        rows: List[List[str]] = []
        raw_markdown = "\n".join(table_lines)

        delimiter_idx = -1
        for idx, line in enumerate(table_lines):
            if cls.TABLE_DELIMITER_REGEX.match(line):
                delimiter_idx = idx
                break

        if delimiter_idx == -1:
            return None

        # Parse header row (before delimiter)
        if delimiter_idx > 0:
            header_line = table_lines[0]
            header_match = cls.TABLE_ROW_REGEX.match(header_line)
            if header_match:
                headers = [
                    cls.clean_heading_title(cell.replace("<br>", " "))
                    for cell in header_match.group(1).split("|")
                ]

        # Parse data rows (after delimiter)
        for line in table_lines[delimiter_idx + 1:]:
            row_match = cls.TABLE_ROW_REGEX.match(line)
            if row_match:
                cells = [
                    cell.strip().replace("<br>", "\n")
                    for cell in row_match.group(1).split("|")
                ]
                # Pad or truncate row cells to match header length if headers exist
                if headers and len(cells) < len(headers):
                    cells.extend([""] * (len(headers) - len(cells)))
                rows.append(cells)

        if not headers and not rows:
            return None

        table_id = f"tbl_{uuid.uuid4().hex[:8]}"
        col_count = len(headers) if headers else (len(rows[0]) if rows else 0)

        return TableData(
            id=table_id,
            section_id=section_id,
            headers=headers,
            rows=rows,
            raw_markdown=raw_markdown,
            row_count=len(rows),
            col_count=col_count,
            page=page_num
        )

    @classmethod
    def extract_tables_from_content(cls, content: str, section_id: str, default_page: int) -> Tuple[str, List[TableData]]:
        """
        Detects and parses tables from section markdown content.
        Returns the content and a list of TableData objects.
        """
        lines = content.split("\n")
        tables: List[TableData] = []
        current_table_lines: List[str] = []
        in_table = False

        for line in lines:
            is_table_row = bool(cls.TABLE_ROW_REGEX.match(line))
            
            if is_table_row:
                in_table = True
                current_table_lines.append(line)
            else:
                if in_table:
                    # Flush table
                    tbl = cls.parse_table_block(current_table_lines, section_id, default_page)
                    if tbl:
                        tables.append(tbl)
                    current_table_lines = []
                    in_table = False

        if in_table and current_table_lines:
            tbl = cls.parse_table_block(current_table_lines, section_id, default_page)
            if tbl:
                tables.append(tbl)

        return content, tables

    @classmethod
    def build_tree_from_page_chunks(
        cls,
        page_chunks: List[Dict[str, Any]],
        filename: str = "document.pdf",
        full_markdown: str = "",
        processing_time: float = 0.0
    ) -> DocumentTree:
        """
        Builds a hierarchical section tree from per-page markdown chunks.
        """
        # Step 1: Collect linear sequence of raw blocks (headings & text spans with page numbers)
        raw_sections: List[Dict[str, Any]] = []
        
        current_section = {
            "id": f"sec_{uuid.uuid4().hex[:8]}",
            "title": "Document Preamble",
            "level": 1,
            "page_start": 1,
            "page_end": 1,
            "lines": [],
            "raw_heading": ""
        }

        first_heading_found = False

        for chunk_idx, chunk in enumerate(page_chunks):
            page_num = chunk.get("metadata", {}).get("page", chunk_idx + 1)
            text = chunk.get("text", "")
            lines = text.split("\n")

            for line in lines:
                heading_match = cls.HEADING_REGEX.match(line)
                if heading_match:
                    hashes, title_text = heading_match.groups()
                    level = len(hashes)
                    clean_title = cls.clean_heading_title(title_text)

                    # If previous section has content or was a real heading, commit it
                    if not first_heading_found:
                        if any(l.strip() for l in current_section["lines"]):
                            raw_sections.append(current_section)
                        first_heading_found = True
                    else:
                        raw_sections.append(current_section)

                    # Start new section
                    current_section = {
                        "id": f"sec_{uuid.uuid4().hex[:8]}",
                        "title": clean_title,
                        "level": level,
                        "page_start": page_num,
                        "page_end": page_num,
                        "lines": [],
                        "raw_heading": line
                    }
                else:
                    current_section["lines"].append(line)
                    current_section["page_end"] = max(current_section["page_end"], page_num)

        # Commit final section
        if current_section["lines"] or current_section["raw_heading"]:
            raw_sections.append(current_section)

        # If no sections at all, create a single fallback section
        if not raw_sections:
            raw_sections.append({
                "id": f"sec_{uuid.uuid4().hex[:8]}",
                "title": "Document Content",
                "level": 1,
                "page_start": 1,
                "page_end": max(len(page_chunks), 1),
                "lines": full_markdown.split("\n") if full_markdown else ["No content found."],
                "raw_heading": "# Document Content"
            })

        # Step 2: Convert raw sections to SectionNode objects with tables and metrics
        node_list: List[SectionNode] = []
        all_tables: List[TableData] = []
        total_words = 0

        for raw_sec in raw_sections:
            content_str = "\n".join(raw_sec["lines"]).strip()
            raw_md = f"{raw_sec['raw_heading']}\n\n{content_str}".strip() if raw_sec["raw_heading"] else content_str
            
            # Words count
            words = len(re.findall(r"\b\w+\b", content_str))
            total_words += words

            # Extract tables
            _, tables = cls.extract_tables_from_content(content_str, raw_sec["id"], raw_sec["page_start"])
            all_tables.extend(tables)

            node = SectionNode(
                id=raw_sec["id"],
                title=raw_sec["title"],
                level=raw_sec["level"],
                page_start=raw_sec["page_start"],
                page_end=raw_sec["page_end"],
                content=content_str,
                raw_markdown=raw_md,
                word_count=words,
                table_count=len(tables),
                tables=tables,
                children=[]
            )
            node_list.append(node)

        # Step 3: Build tree hierarchy (nesting by heading level)
        # We use a virtual root node with level 0
        virtual_root = SectionNode(
            id="root_virtual",
            title="Root",
            level=0,
            page_start=1,
            page_end=max(len(page_chunks), 1),
            content="",
            raw_markdown="",
            word_count=0,
            table_count=0,
            tables=[],
            children=[]
        )

        stack: List[SectionNode] = [virtual_root]
        flat_map: Dict[str, Any] = {}

        for node in node_list:
            # Pop stack while top node level is >= current node level
            while stack and stack[-1].level >= node.level:
                stack.pop()

            parent = stack[-1] if stack else virtual_root
            parent.children.append(node)
            stack.append(node)

        # Step 4: Recursively calculate page_end for parent nodes and populate flat_map
        def finalize_node(n: SectionNode) -> Tuple[int, int]:
            max_p = n.page_end
            min_p = n.page_start
            
            for child in n.children:
                child_min, child_max = finalize_node(child)
                max_p = max(max_p, child_max)
                min_p = min(min_p, child_min)

            n.page_end = max_p
            n.page_start = min_p

            if n.id != "root_virtual":
                flat_map[n.id] = {
                    "id": n.id,
                    "title": n.title,
                    "level": n.level,
                    "page_start": n.page_start,
                    "page_end": n.page_end,
                    "word_count": n.word_count,
                    "table_count": n.table_count,
                    "has_children": len(n.children) > 0,
                    "child_ids": [c.id for c in n.children],
                }
            return min_p, max_p

        for root_child in virtual_root.children:
            finalize_node(root_child)

        return DocumentTree(
            filename=filename,
            total_pages=len(page_chunks),
            total_sections=len(node_list),
            total_tables=len(all_tables),
            total_words=total_words,
            toc=virtual_root.children,
            flat_sections=flat_map,
            raw_markdown=full_markdown,
            processing_time_sec=round(processing_time, 2)
        )
